# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    expose:
        - 5432
    environment:
      POSTGRES_PASSWORD: 102938
      POSTGRES_DB: db
  web:
    build: .
    command: python3 ./mda/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
