# Generated by Django 2.0.3 on 2018-03-28 16:15

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price', models.IntegerField()),
                ('rating', models.IntegerField(validators=[products.models.ratingCheck])),
                ('description', models.TextField()),
                ('likes', models.IntegerField()),
            ],
        ),
    ]
