# Generated by Django 2.0.3 on 2018-03-28 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180328_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userseller',
            old_name='user_id',
            new_name='user',
        ),
    ]
