# Generated by Django 2.0.3 on 2018-03-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180328_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=89055255582, max_length=32),
            preserve_default=False,
        ),
    ]
