# Generated by Django 2.0.3 on 2018-03-28 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_userbuyer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
        migrations.AlterModelTable(
            name='userbuyer',
            table='buyers',
        ),
        migrations.AlterModelTable(
            name='userseller',
            table='sellers',
        ),
    ]
